# Generated by Django 4.2.7 on 2025-11-22 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('pickup_address', models.TextField(help_text='Full pickup address')),
                ('delivery_address', models.TextField(help_text='Full delivery address')),
                ('parcel_weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of parcels')),
                ('parcel_image', models.ImageField(blank=True, null=True, upload_to='parcels/%Y/%m/')),
                ('length', models.DecimalField(decimal_places=2, help_text='Length in cm', max_digits=10)),
                ('width', models.DecimalField(decimal_places=2, help_text='Width in cm', max_digits=10)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Additional notes or description')),
                ('status', models.CharField(choices=[('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('PICKED', 'Picked'), ('ON_THE_WAY', 'On the Way'), ('DELIVERED', 'Delivered')], default='UNDER_REVIEW', max_length=20)),
                ('courier_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='orders.order')),
            ],
            options={
                'verbose_name': 'User Delivery',
                'verbose_name_plural': 'User Deliveries',
                'db_table': 'user_deliveries',
                'unique_together': {('order', 'customer')},
            },
        ),
    ]
