# Generated by Django 4.2.7 on 2025-11-24 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, default=10.0, help_text='Base price for any delivery (NZD)', max_digits=10)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=1.5, help_text='Price per kilometer (NZD)', max_digits=10)),
                ('price_per_kg', models.DecimalField(decimal_places=2, default=2.0, help_text='Price per kilogram (NZD)', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Configuration',
                'verbose_name_plural': 'Pricing Configuration',
                'db_table': 'pricing_configuration',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='auto_calculated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated based on distance', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_proof_image',
            field=models.ImageField(blank=True, help_text='Photo taken at delivery (Admin only)', null=True, upload_to='delivery_proof/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='order',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance in kilometers', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='parcel_type',
            field=models.CharField(choices=[('GENERAL', 'General Items'), ('FRAGILE', 'Fragile/Glass'), ('ELECTRONICS', 'Electronics'), ('DOCUMENTS', 'Documents'), ('FOOD', 'Food Items'), ('GIFT', 'Gift Items'), ('FOAM', 'Foam/Soft Items'), ('CLOTHING', 'Clothing'), ('BOOKS', 'Books/Media'), ('OTHER', 'Other')], default='GENERAL', help_text='Type of parcel', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='parcel_image',
            field=models.ImageField(help_text='Photo of the parcel (Required)', upload_to='parcels/%Y/%m/'),
        ),
        migrations.CreateModel(
            name='OrderConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concern_type', models.CharField(choices=[('DAMAGED', 'Parcel Damaged'), ('MISSING_ITEMS', 'Missing Items'), ('WRONG_DELIVERY', 'Wrong Delivery Address'), ('DELAY', 'Excessive Delay'), ('OTHER', 'Other Issue')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('concern_image', models.ImageField(blank=True, help_text='Photo of the issue', null=True, upload_to='concerns/%Y/%m/')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('admin_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerns', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concerns', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Concern',
                'verbose_name_plural': 'Order Concerns',
                'db_table': 'order_concerns',
                'ordering': ['-created_at'],
            },
        ),
    ]
