# Generated by Django 4.2.7 on 2025-11-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pricingconfiguration_order_auto_calculated_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Customer's counter-offer or preferred price", max_digits=10, null=True),
        ),
    ]
