# Generated by Django 4.2.7 on 2025-11-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_customer_proposed_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfiguration',
            name='allow_customer_negotiation',
            field=models.BooleanField(default=True, help_text='Allow customers to propose their own price'),
        ),
    ]
