# Generated by Django 4.2.7 on 2025-11-29 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_pricingconfiguration_allow_customer_negotiation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySpeedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('SAME_DAY', 'Same Day Delivery (8AM-6PM)'), ('OVERNIGHT', 'Overnight Delivery'), ('EXPRESS_90MIN', '90 Minutes Express')], help_text='Delivery speed code', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description for customers')),
                ('adjustment_type', models.CharField(choices=[('PER_KM', 'Per Kilometer'), ('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PER_KM', help_text='How to adjust the price', max_length=20)),
                ('adjustment_value', models.DecimalField(decimal_places=2, default=0, help_text='Adjustment value (e.g., 1 for $1/km, 10 for 10%, or fixed $50)', max_digits=10)),
                ('requires_admin_approval', models.BooleanField(default=False, help_text='Require admin approval for this speed')),
                ('cutoff_time', models.TimeField(blank=True, help_text='Order cutoff time (e.g., 1:00 PM for same-day)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this option')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Delivery Speed Option',
                'verbose_name_plural': 'Delivery Speed Options',
                'db_table': 'delivery_speed_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tier name (e.g., "Light Package")', max_length=100)),
                ('weight_min', models.DecimalField(decimal_places=2, help_text='Minimum weight in KG (inclusive)', max_digits=10)),
                ('weight_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight in KG (inclusive). Leave blank for no limit', max_digits=10, null=True)),
                ('distance_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Distance threshold in KM (e.g., 10). Leave blank if no distance condition', max_digits=10, null=True)),
                ('price_per_km_short', models.DecimalField(decimal_places=2, help_text='Price per KM for distances ≤ threshold', max_digits=10)),
                ('price_per_km_long', models.DecimalField(blank=True, decimal_places=2, help_text='Price per KM for distances > threshold. Leave blank if same as short distance', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this tier')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Pricing Tier',
                'verbose_name_plural': 'Pricing Tiers',
                'db_table': 'pricing_tiers',
                'ordering': ['order', 'weight_min'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_speed',
            field=models.CharField(default='SAME_DAY', help_text='Delivery speed option', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricingconfiguration',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='LEGACY: Base price (use Pricing Tiers instead)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricingconfiguration',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='LEGACY: Price per KG (use Pricing Tiers instead)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricingconfiguration',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='LEGACY: Price per KM (use Pricing Tiers instead)', max_digits=10),
        ),
    ]
