# Generated by Django 4.2.7 on 2025-12-06 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_deliveryspeedoption_pricingtier_order_delivery_speed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('EXPRESS_2HR', 'Helpii Express (2 Hour Urgent)'), ('SAME_DAY', 'Helpii Same Day'), ('OVERNIGHT', 'Helpii Overnight')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=10.0, help_text='Base price for this delivery type', max_digits=10)),
                ('max_coverage_km', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum coverage in KM (e.g., 30 for Auckland metro)', max_digits=10, null=True)),
                ('requires_admin_approval', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Delivery Type',
                'verbose_name_plural': 'Delivery Types',
                'db_table': 'delivery_types',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='is_oversize',
            field=models.BooleanField(default=False, help_text='Item is too large for a standard car (e.g., >1m length, bulky)'),
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rule name for admin (e.g., "Same Day Small Short Trip")', max_length=100)),
                ('weight_category', models.CharField(choices=[('SMALL', 'Small (≤10 kg)'), ('MEDIUM', 'Medium (11-20 kg)'), ('HEAVY', 'Heavy (>20 kg)'), ('ANY', 'Any Weight')], default='ANY', max_length=20)),
                ('weight_min', models.DecimalField(decimal_places=2, default=0, help_text='Minimum weight in KG', max_digits=10)),
                ('weight_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight in KG (leave blank for no limit)', max_digits=10, null=True)),
                ('is_oversize_rule', models.BooleanField(default=False, help_text='This rule applies to oversize items only')),
                ('distance_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='KM threshold for short/long trips (e.g., 10)', max_digits=10, null=True)),
                ('is_short_trip', models.BooleanField(blank=True, help_text='True=short trip (≤threshold), False=long trip (>threshold), None=any distance', null=True)),
                ('calculation_type', models.CharField(choices=[('PER_KM', 'Rate per KM (base + rate×km)'), ('CAPPED', 'Capped Total (base + rate×km, max cap)'), ('FLAT', 'Flat Total Price')], default='PER_KM', max_length=20)),
                ('rate_per_km', models.DecimalField(blank=True, decimal_places=2, help_text='Rate per KM (for PER_KM type)', max_digits=10, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum capped price (for CAPPED type)', max_digits=10, null=True)),
                ('flat_total', models.DecimalField(blank=True, decimal_places=2, help_text='Flat total price (for FLAT type)', max_digits=10, null=True)),
                ('oversize_surcharge', models.DecimalField(decimal_places=2, default=0, help_text='Additional surcharge for oversize items', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Lower number = higher priority for matching')),
                ('delivery_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='orders.deliverytype')),
            ],
            options={
                'verbose_name': 'Pricing Rule',
                'verbose_name_plural': 'Pricing Rules',
                'db_table': 'pricing_rules',
                'ordering': ['delivery_type', 'priority', 'weight_min'],
            },
        ),
    ]
