# Generated by Django 4.2.7 on 2025-12-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_deliverytype_order_is_oversize_pricingrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='height',
        ),
        migrations.RemoveField(
            model_name='order',
            name='length',
        ),
        migrations.RemoveField(
            model_name='order',
            name='width',
        ),
    ]
