# Generated by Django 4.2.7 on 2025-12-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_dimension_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingconfiguration',
            name='show_distance_to_customer',
            field=models.BooleanField(default=False, help_text='Show calculated distance (KM) to customers on order form'),
        ),
    ]
